package bochoVJ.wii;

public interface IWiiManager {

	/**
	 * Gets the battery level of the device.
	 * @return returns the battery level
	 */
	public abstract double getBatteryLevel();

	/**
	 * Adds an handler to the events generated by the WiiMote.
	 * @param han
	 */
	public abstract void addHandler(IWiiHandler han);
	
	/**
	 * Removes an handler from the manager.
	 * @param han
	 */
	public abstract void removeHandler(IWiiHandler han);

	/**
	 * Connects to the Wii Mote.
	 * @throws Exception 
	 */
	public abstract void connect() throws Exception;

	/**
	 * Disconnects from the mote.
	 */
	public abstract void disconnect();

}